name: toku_app_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

# ğŸ‘‡ Ø¯Ù‡ Ù„Ø§Ø²Ù… ÙŠÙƒÙˆÙ† Ø¨Ø±Ø§ dependencies Ùˆ dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/numbers/
    - assets/images/family_members/
    - assets/images/colors/
    - assets/sounds/numbers/
    - assets/sounds/family_members/
    - assets/sounds/colors/
    - assets/sounds/phrases/
